#:include buiding.kv

FloatLayout:
    Background:
        id: background
        canvas.before:
            Rectangle:
                size: self.size
                pos: self.pos
                source: "BG.png"
            Rectangle:
                size: self.width, 96
                pos: self.pos[0], self.pos[1]
                texture: self.floor_texture
    Button:
        text: "Start game"
        on_release:
            app.start_game()